// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJGRt-8wAJfB_gJ3JQBBYrZsNGCa1T88',
    appId: '1:724500024177:web:cff0669e939f810c8244d0',
    messagingSenderId: '724500024177',
    projectId: 'whatsappchatinterface',
    authDomain: 'whatsappchatinterface.firebaseapp.com',
    storageBucket: 'whatsappchatinterface.appspot.com',
    measurementId: 'G-ZG5LL6644E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_B_F18dmL7WWmpJ73O_XVYH6ge8-T20',
    appId: '1:724500024177:android:11834c37277b3dc38244d0',
    messagingSenderId: '724500024177',
    projectId: 'whatsappchatinterface',
    storageBucket: 'whatsappchatinterface.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycczu0NdS9rNCEbCKfEd_XEqi5liDuoQ',
    appId: '1:724500024177:ios:82725173125ee0498244d0',
    messagingSenderId: '724500024177',
    projectId: 'whatsappchatinterface',
    storageBucket: 'whatsappchatinterface.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycczu0NdS9rNCEbCKfEd_XEqi5liDuoQ',
    appId: '1:724500024177:ios:84d58ea29b9b679f8244d0',
    messagingSenderId: '724500024177',
    projectId: 'whatsappchatinterface',
    storageBucket: 'whatsappchatinterface.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
